# YML是一种文件格式，全称为YAML（YAML Ain't Markup Language），SpringBoot通常使用YML作为项目配置。
# 它是一种人类可读的、简洁明了的数据序列化格式。YAML文件格式通常用于配置文件、数据交换、消息传递和其他应用程序。
# 可以通过文本编辑器进行编辑，也可以通过程序进行解析。YML文件格式是一种以层级缩进的方式表示程序数据结构的格式。
# 在数据表示方面比XML等格式更加简洁清晰易读。YML文件格式通常以“.yml”为扩展名。

#服务端口等配置
server:
  port: 9111
  servlet:
   context-path: /BookManager

spring:
  #数据库配置
  datasource:
   driver-class-name: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://localhost:3306/DB_Book?useAffectedRows=true
   username: root
   password: xiao

  #Redis配置
  redis:
   host: localhost
   port: 6379
   password:

  #Servlet配置（文件上传大小限制等）
  servlet:
   multipart:
    max-file-size: 10MB
    max-request-size: 100MB
    enabled: false

 #mybatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml

